'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let project=null,report=null,step='board',kind='bom',field='ref',page=0,lib=[],selectedGroup=null,editingPart=null,markDefaults={},markTemplates=[];
const schemas={bom:[['ref','位号 *'],['name','物料名称'],['spec','规格型号'],['partno','物料编号'],['qty','数量'],['footprint','封装']],cad:[['ref','位号 *'],['x','X *'],['y','Y *'],['rotation','角度 *'],['side','加工面'],['footprint','封装']]};
const labels={LightingOuter:'外环光源',LightingInner:'内环光源',LightingDrop:'同轴光源',LightingIROuter:'红外外环',LightingIRInner:'红外内环',FilterInner:'内环过滤值',FilterOuter:'外环过滤值',Surface:'明暗面 Surface',Threshold:'阈值',Tolerance:'容差',SearchAreaX:'搜索 X / mm',SearchAreaY:'搜索 Y / mm',Sequence:'识别顺序',PartsName:'元件名称',BodyX:'本体 X / mm',BodyY:'本体 Y / mm',BodyZ:'高度 / mm',Nozzle:'吸嘴编号',NozzleEx:'扩展吸嘴编号',FdrType:'Feeder 类型值',CarrierTape:'载带类型值',FdrIdxStep:'送料步距值',PitchEffect:'送料间距值',Setno:'来源站位',Comment:'备注'};
async function api(path,method='GET',body){
  const options={method};if(body instanceof FormData)options.body=body;else if(body!==undefined){options.headers={'Content-Type':'application/json'};options.body=JSON.stringify(body);}
  const response=await fetch('/api'+path,options);const data=await response.json();
  if(!response.ok)throw new Error((data.errors||[{message:JSON.stringify(data)}]).map(e=>`${e.code||''}: ${e.message}`).join('\n'));
  return data;
}
function toast(text){$('toast').textContent=text;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').textContent='',10000);}
let actionQueue=Promise.resolve();
function run(fn){return event=>{if(event?.type==='submit')event.preventDefault();actionQueue=actionQueue.then(async()=>{document.body.setAttribute('aria-busy','true');try{await fn(event);}catch(error){toast(error.message);}finally{document.body.removeAttribute('aria-busy');}});return actionQueue;};}
function requireProject(){if(!project)throw new Error('请先新建或打开项目');}
const path=s=>`/projects/${project.id}${s}`;
async function upload(url,file){if(!file)throw new Error('请选择文件');const data=new FormData();data.append('file',file);return api(url,'POST',data);}
async function listProjects(){const items=await api('/projects');$('projectList').innerHTML='<option value="">选择已保存项目</option>'+items.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if(project)$('projectList').value=project.id;}
async function refresh(){const loaded=await api(path(''));const analysis=await api(path('/analyze'),'POST');const items=await api(path('/library'));project=loaded;report=analysis;lib=items;$('projectName').textContent=`${project.name} · 已保存 r${project.revision}`;$('saveProject').href='/api'+path('/save');$('saveProject').download=project.name+'.ybproject.json';render();renderBoard();}
async function openProject(id){project=await api(`/projects/${id}`);step=Object.keys(project.tables).length?'tables':(project.board.width?'marks':'board');await refresh();}
$('newProject').onclick=run(async()=>{const name=prompt('程序 / 项目名称');if(!name)return;project=await api('/projects','POST',{name});await listProjects();await refresh();openBoard();});
$('projectList').onchange=run(async e=>{if(e.target.value)await openProject(e.target.value);});
$('loadProject').onchange=run(async e=>{project=await upload('/projects/load',e.target.files[0]);await listProjects();await openProject(project.id);e.target.value='';});
$('renameProject').onclick=run(async()=>{requireProject();const name=prompt('程序名称',project.name);if(name){await api(path('/name'),'PUT',{name});await refresh();await listProjects();}});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('steps').onclick=run(async e=>{const b=e.target.closest('[data-step]');if(!b)return;requireProject();step=b.dataset.step;render();if(step==='board')openBoard();if(step==='marks')openMarks();});
function openBoard(){requireProject();const f=$('boardForm');f.reset();for(const [k,v]of Object.entries(project.board)){if(f.elements[k])f.elements[k].value=v;} renderBoardEditor();$('boardDialog').showModal();}
$('boardForm').onsubmit=run(async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));for(const k of ['width','height','thickness','offset_x','offset_y','ygx_origin_x','ygx_origin_y','hole_margin_x','hole_margin_y']){if(values[k]==='')delete values[k];else values[k]=Number(values[k]);}await api(path('/board'),'PUT',values);$('boardDialog').close();step='marks';await refresh();openMarks();});
function templateParameters(xml){
  const doc=new DOMParser().parseFromString(xml,'application/xml');
  const attrs=tag=>Object.fromEntries([...(doc.querySelector(tag)?.attributes||[])].map(a=>[a.name,a.value]));
  return {lighting:attrs('Mark_200'),vision:attrs('Mark_100')};
}
function templateHasSize(xml){return !!new DOMParser().parseFromString(xml,'application/xml').querySelector('Mark_011,Mark_020');}
$('markRows').onchange=e=>{
  if(e.target.name!=='shape')return;
  const marks=readMarks(),index=Number(e.target.closest('.mark-card').dataset.index),mark=marks[index];
  if(mark.shape==='template'){
    Object.assign(mark,templateParameters(mark.template_xml));
    const doc=new DOMParser().parseFromString(mark.template_xml,'application/xml'),circle=doc.querySelector('Mark_011'),rect=doc.querySelector('Mark_020');
    if(circle)mark.width=mark.height=Number(circle.getAttribute('OutSize'));
    if(rect){mark.width=Number(rect.getAttribute('OutSizeX'));mark.height=Number(rect.getAttribute('OutSizeY'));}
  }else{delete mark.template_xml;Object.assign(mark,markDefaults[mark.shape]);}
  markRows(marks);
};
function markRows(settings){
  $('markRows').innerHTML=settings.map((m,i)=>{const shape=m.shape||'circle',defaults=shape==='template'?templateParameters(m.template_xml):markDefaults[shape];const custom=shape==='template'&&!templateHasSize(m.template_xml);return `<div class="mark-card" data-index="${i}"><h3>MARK ${i+1}</h3><div class="formgrid"><label>中心 X<input name="x" type="number" step="any" value="${m.x}" required></label><label>中心 Y<input name="y" type="number" step="any" value="${m.y}" required></label><label>形状<select name="shape"><option value="circle" ${shape==='circle'?'selected':''}>圆形</option><option value="rectangle" ${shape==='rectangle'?'selected':''}>矩形</option>${markTemplates.map((t,n)=>`<option value="template:${n}" ${m.template_xml===t.xml?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>直径 / 宽 X / mm<input name="width" type="number" step="any" min="0.001" value="${m.width||1}" ${custom?'readonly':''} required></label><label>高 Y / mm（圆形忽略）<input name="height" type="number" step="any" min="0.001" value="${m.height||m.width||1}" ${custom?'readonly':''} required></label></div>${custom?'<p class="muted">此模板的图形尺寸保留原 XML；宽高只表示校验边界。修改图形请导入更新后的模板。</p>':''}<details open><summary>光源设置</summary><div class="params">${Object.entries({...defaults.lighting,...m.lighting}).map(([k,v])=>`<label>${esc(labels[k]||k)}<input data-section="lighting" name="${k}" type="number" step="any" min="0" value="${v}"></label>`).join('')}</div></details><details><summary>明暗、阈值与搜索区域</summary><div class="params">${Object.entries({...defaults.vision,...m.vision}).map(([k,v])=>`<label>${esc(labels[k]||k)}<input data-section="vision" name="${k}" type="number" step="any" min="0" value="${v}"></label>`).join('')}</div></details></div>`;}).join('');
}
function readMarks(){return [...$('markRows').children].map(card=>{const m={lighting:{},vision:{}};card.querySelectorAll('input,select').forEach(input=>{if(input.dataset.section)m[input.dataset.section][input.name]=Number(input.value);else m[input.name]=input.name==='shape'?input.value:Number(input.value);});if(m.shape.startsWith('template:')){m.template_xml=markTemplates[Number(m.shape.split(':')[1])].xml;m.shape='template';}return m;});}
function openMarks(){requireProject();if(!project.board.width){openBoard();return;}for(const m of project.marks){if(m.template_xml&&!markTemplates.some(t=>t.xml===m.template_xml))markTemplates.push({name:'已保存自定义 MARK',xml:m.template_xml});}const marks=project.marks.length?project.marks:[{x:5,y:5,width:1,height:1},{x:project.board.width-5,y:project.board.height-5,width:1,height:1}];$('markCount').value=String(marks.length);markRows(marks);$('markDialog').showModal();}
$('markCount').onchange=()=>{const marks=readMarks();if($('markCount').value==='3'&&marks.length===2)marks.push({x:project.board.width-5,y:5,width:1,height:1});markRows(marks.slice(0,Number($('markCount').value)));};
$('markTemplateFile').onchange=run(async e=>{const marks=readMarks();markTemplates.push(...await upload('/mark-templates',e.target.files[0]));markRows(marks);e.target.value='';});
$('markForm').onsubmit=run(async e=>{e.preventDefault();await api(path('/marks'),'PUT',readMarks());$('markDialog').close();step='tables';await refresh();});
function render(){
  document.querySelectorAll('[data-step]').forEach(b=>b.classList.toggle('active',b.dataset.step===step));
  if(!project)return;
  const w=$('workspace');
  if(step==='board'){const b=project.board;w.innerHTML=`<h2>板信息</h2><p>${b.width?`${b.width} × ${b.height} × ${b.thickness} mm · ${b.side}`:'尚未填写'}</p><p class="muted">输入单位 ${esc(b.units||'mm')}，坐标变换 ${esc(b.transform||'none')}。</p><button class="btn primary" id="editBoard">修改板信息</button><details class="section"><summary>程序结构模板</summary><p class="muted">默认采用已验证的 YSM20 YGX 结构。可以导入其他已可用 YGX 保留相应机型结构。</p><label class="filelabel">导入 YGX 模板<input id="templateFile" type="file" accept=".ygx"></label></details>`;$('editBoard').onclick=openBoard;$('templateFile').onchange=run(async e=>{await upload(path('/template'),e.target.files[0]);await refresh();});}
  if(step==='marks'){w.innerHTML=`<h2>MARK 设置</h2>${project.marks.map((m,i)=>`<p>MARK ${i+1}：(${m.x}, ${m.y}) · ${esc(m.shape)} · ${m.width} × ${m.height} mm</p>`).join('')}<button class="btn primary" id="editMarks">修改 MARK 与光源</button>`;$('editMarks').onclick=openMarks;}
  if(step==='assembly'){openAssembly().catch(e=>toast(e.message));}
  if(step==='tables')renderTable();
  if(step==='library')renderGroups();
  if(step==='export')renderExport();
}
function renderTable(){
  const t=project.tables[kind],w=$('workspace');
  w.innerHTML=`<h2>BOM / CAD 整理</h2><div class="toolbar"><button class="btn ${kind==='bom'?'secondary':'ghost'}" id="bomTab">BOM</button><button class="btn ${kind==='cad'?'secondary':'ghost'}" id="cadTab">CAD</button><label class="filelabel">导入 ${kind.toUpperCase()}<input id="tableFile" type="file" accept=".csv,.txt,.tsv,.xlsx,.xls"></label></div><p class="muted">选择字段，再点击表格中的列。点击左侧复选框排除/恢复行；点击“表头”指定数据开始位置。</p>${t?`<div class="muted">${esc(t.filename)} · ${esc(t.encoding)} · 原始 ${t.rows.length} 行 · 排除 ${t.excluded_rows.length} 行</div><div class="fieldbar">${schemas[kind].map(([k,n])=>`<button class="fieldbtn ${field===k?'selected':''} ${k in t.mapping?'done':''}" data-field="${k}">${n}${k in t.mapping?` → 列 ${t.mapping[k]+1}`:''}</button>`).join('')}<button class="clearbtn" id="clearField">取消当前字段绑定</button></div><div class="toolbar"><button class="btn ghost" id="prevPage">上一页</button><span>第 ${page+1} / ${Math.max(1,Math.ceil(t.rows.length/100))} 页</span><button class="btn ghost" id="nextPage">下一页</button><button class="btn primary" id="toLibrary">整理完成，匹配元件库</button></div><div class="preview" id="rawTable"></div>`:'<p>请导入文件。</p>'}`;
  $('bomTab').onclick=()=>{kind='bom';page=0;renderTable();};$('cadTab').onclick=()=>{kind='cad';page=0;renderTable();};
  $('tableFile').onchange=run(async e=>{await upload(path(`/tables/${kind}`),e.target.files[0]);page=0;await refresh();});
  if(!t)return;
  w.querySelectorAll('[data-field]').forEach(b=>b.onclick=()=>{field=b.dataset.field;renderTable();});
  $('clearField').onclick=()=>{const targetKind=kind,targetField=field;return run(async()=>{const current=project.tables[targetKind],mapping={...current.mapping};delete mapping[targetField];await configure(mapping,current.excluded_rows,current.header_row,targetKind);})();};
  $('prevPage').onclick=()=>{page=Math.max(0,page-1);renderTable();};$('nextPage').onclick=()=>{page=Math.min(Math.ceil(t.rows.length/100)-1,page+1);renderTable();};
  $('toLibrary').onclick=async()=>{step='library';render();};
  const count=Math.max(...t.rows.map(r=>r.cells.length));const header=t.rows.find(r=>r.id===t.header_row)?.cells||[];
  $('rawTable').innerHTML=`<table class="raw"><thead><tr><th>排除</th><th>原行号</th><th>表头</th>${Array.from({length:count},(_,i)=>`<th data-col="${i}" class="${Object.values(t.mapping).includes(i)?'mapped':''}">列 ${i+1} · ${esc(header[i]||'')}<span class="field-tag">${Object.entries(t.mapping).filter(([,v])=>v===i).map(([k])=>k).join(', ')}</span></th>`).join('')}</tr></thead><tbody>${t.rows.slice(page*100,(page+1)*100).map(r=>`<tr class="${t.excluded_rows.includes(r.id)?'excluded':''}"><td><input type="checkbox" data-row="${r.id}" ${t.excluded_rows.includes(r.id)?'checked':''} aria-label="排除行 ${r.id+1}"></td><td>${r.id+1}</td><td><button data-header="${r.id}">${r.id===t.header_row?'当前表头':'设表头'}</button></td>${Array.from({length:count},(_,i)=>`<td data-col="${i}" title="${esc(r.cells[i]||'')}">${esc(r.cells[i]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  $('rawTable').onclick=e=>{const targetKind=kind,targetField=field,col=e.target.dataset.col,header=e.target.dataset.header;if(col===undefined&&header===undefined)return;return run(async()=>{const current=project.tables[targetKind];const mapping=col===undefined?current.mapping:{...current.mapping,[targetField]:Number(col)};await configure(mapping,current.excluded_rows,header===undefined?current.header_row:Number(header),targetKind);})();};
  $('rawTable').onchange=e=>{if(e.target.dataset.row===undefined)return;const targetKind=kind,id=Number(e.target.dataset.row),checked=e.target.checked;return run(async()=>{const current=project.tables[targetKind],excluded=new Set(current.excluded_rows);if(checked)excluded.add(id);else excluded.delete(id);await configure(current.mapping,[...excluded],current.header_row,targetKind);})();};
}
async function configure(mapping,excluded_rows,header_row,targetKind=kind){await api(path(`/tables/${targetKind}`),'PUT',{mapping,excluded_rows,header_row});await refresh();}
function renderGroups(){
  $('workspace').innerHTML=`<h2>连接元件库</h2><div class="toolbar"><label class="filelabel">导入元件库 ZIP / FDX / YGX<input id="libraryFile" type="file" accept=".zip,.fdx,.ygx,.xml"></label><button class="btn ghost" id="browseLibrary">浏览 / 编辑库</button><button class="btn primary" id="toExport">校验与导出</button></div><p class="muted">${lib.length} 条库记录。候选不会自动确认；同封装的不同 BOM 物料保持独立。</p><div class="preview"><table><thead><tr><th>物料 / 规格</th><th>封装</th><th>点数</th><th>库匹配</th><th>操作</th></tr></thead><tbody>${report.groups.map(g=>`<tr><td title="${esc(g.refs.join(', '))}">${esc(g.name)}<br><span class="muted">${esc(g.spec)} · ${esc(g.partno||g.program_name)}</span></td><td>${esc(g.footprint)}</td><td>${g.refs.length}</td><td>${g.part_id?`<span class="ok">${esc(g.library_name||'已匹配')}</span>`:`<span class="warn">待确认${g.candidates.length?' · 有候选':''}</span>`}</td><td><button class="btn ghost" data-group="${g.id}">选择库</button>${g.part_id?`<button class="btn ghost" data-edit="${g.part_id}">编辑参数</button><button class="btn ghost" data-unmatch="${g.id}">取消</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;
  $('libraryFile').onchange=run(async e=>{await upload(path('/library'),e.target.files[0]);await refresh();});
  $('browseLibrary').onclick=()=>openLibrary(null);$('toExport').onclick=()=>{step='export';render();};
  $('workspace').querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>openLibrary(b.dataset.group));
  $('workspace').querySelectorAll('[data-edit]').forEach(b=>b.onclick=run(()=>openPart(b.dataset.edit)));
  $('workspace').querySelectorAll('[data-unmatch]').forEach(b=>b.onclick=run(async()=>{await api(path(`/matches/${b.dataset.unmatch}`),'PUT',{part_id:null});await refresh();}));
}
function openLibrary(gid){selectedGroup=gid;$('libraryTitle').textContent=gid?'为当前物料选择库记录':'浏览元件库';$('librarySearch').value='';renderChoices();$('libraryDialog').showModal();}
function renderChoices(){const q=$('librarySearch').value.toLowerCase(),group=report.groups.find(g=>g.id===selectedGroup),candidates=new Map((group?.candidates||[]).map(c=>[c.id,c.reason]));const filtered=lib.filter(i=>(i.name+' '+i.source).toLowerCase().includes(q)).sort((a,b)=>Number(candidates.has(b.id))-Number(candidates.has(a.id)));$('libraryChoices').innerHTML=`<p class="muted">${filtered.length} 个结果，显示前 100 个；请输入名称缩小范围。</p><table><thead><tr><th>名称 / 来源</th><th>依据</th><th>操作</th></tr></thead><tbody>${filtered.slice(0,100).map(i=>`<tr><td>${esc(i.name)}<br><span class="muted">${esc(i.source)} · 源编号 ${esc(i.source_no)}</span></td><td>${esc(candidates.get(i.id)||'人工选择')}</td><td>${selectedGroup?`<button class="btn primary" data-select="${i.id}">确认匹配</button>`:''}<button class="btn ghost" data-part="${i.id}">查看 / 编辑</button></td></tr>`).join('')}</tbody></table>`;$('libraryChoices').querySelectorAll('[data-select]').forEach(b=>b.onclick=run(async()=>{await api(path(`/matches/${selectedGroup}`),'PUT',{part_id:b.dataset.select});$('libraryDialog').close();await refresh();}));$('libraryChoices').querySelectorAll('[data-part]').forEach(b=>b.onclick=run(()=>openPart(b.dataset.part)));}
$('librarySearch').oninput=renderChoices;
async function openPart(id){editingPart=await api(path(`/library/${id}`));$('partTitle').textContent=editingPart.name;$('partFields').innerHTML=Object.entries(editingPart.fields).map(([tag,attrs])=>`<details class="section" ${['Part_001','Part_002','Part_003','Part_012','Part_013','Part_080'].includes(tag)?'open':''}><summary>${esc(tag)}</summary><div class="params">${Object.entries(attrs).map(([k,v])=>`<label>${esc(labels[k]||k)}<input data-tag="${tag}" data-attr="${k}" value="${esc(v)}"></label>`).join('')}</div></details>`).join('');$('partXml').value=editingPart.xml;renderPartDiagram();$('partDialog').showModal();}
$('partForm').onsubmit=run(async e=>{e.preventDefault();const changes={};$('partFields').querySelectorAll('input').forEach(i=>{if(i.value!==editingPart.fields[i.dataset.tag][i.dataset.attr]){changes[i.dataset.tag]??={};changes[i.dataset.tag][i.dataset.attr]=i.value;}});await api(path(`/library/${editingPart.id}`),'PUT',{changes});$('partDialog').close();await refresh();if($('libraryDialog').open)renderChoices();});
$('savePartXml').onclick=run(async()=>{await api(path(`/library/${editingPart.id}`),'PUT',{xml:$('partXml').value});$('partDialog').close();await refresh();if($('libraryDialog').open)renderChoices();});
$('duplicatePart').onclick=run(async()=>{const name=prompt('新元件名称',editingPart.name+'_copy');if(!name)return;await api(path(`/library/${editingPart.id}/duplicate`),'POST',{name});$('partDialog').close();await refresh();if($('libraryDialog').open)renderChoices();});
function renderExport(){const good=report.errors.length===0;$('workspace').innerHTML=`<h2>校验与导出</h2><div class="notice ${good?'good':'error'}">${good?'结构校验通过，可以生成 YGX。':`还有 ${report.errors.length} 个问题需要处理。`}</div><p>${report.summary.mounts} 个贴装点 · ${report.summary.groups} 个独立物料 · ${report.summary.matched} 个已匹配</p><p class="muted">输出未优化 YGX，包含板信息、完整 MARK 和元件参数；同时输出本项目 FDX。文件路径会显示在下方。</p><button class="btn primary" id="generate" ${good?'':'disabled'}>生成 YGX</button><div class="outputs" id="exportLinks">${project.exports.slice().reverse().map(exportItem).join('')}</div><details class="section"><summary>被排除的 CAD 位号（${report.excluded.length}）</summary><p>${esc(report.excluded.map(i=>i.ref).join(', '))}</p></details>`;$('generate').onclick=run(async e=>{e.target.disabled=true;try{await api(path('/export'),'POST');await refresh();}finally{if($('generate'))$('generate').disabled=report.errors.length>0;}});}
function exportItem(item){return `<div class="notice">${item.historical?'<span>恢复的导出历史 · 请重新生成文件</span>':`<a download class="link" href="/api${path(`/exports/${item.export_id}/ygx`)}">下载 YGX</a><a download class="link" href="/api${path(`/exports/${item.export_id}/fdx`)}">下载项目元件库 FDX</a>`}<p class="muted">${esc(item.path)}</p><span class="muted">${item.mounts} 点 · SHA256 ${esc(item.sha256)}</span></div>`;}
function renderBoard(){const b=project.board;if(!b.width){$('boardPreview').innerHTML='';return;}const pad=7;$('boardPreview').setAttribute('viewBox',`${-pad} ${-pad} ${b.width+2*pad} ${b.height+2*pad}`);const factor={mm:1,inch:25.4,mil:0.0254}[b.units||'mm'];const convert=m=>{let x=m.x*factor-(b.offset_x||0),y=m.y*factor-(b.offset_y||0);if(['mirror_x','rotate_180'].includes(b.transform))x=b.width-x;if(['mirror_y','rotate_180'].includes(b.transform))y=b.height-y;return {x,y:b.height-y};};$('boardPreview').innerHTML=`<rect x="0" y="0" width="${b.width}" height="${b.height}" fill="#0b2523" stroke="#38bdf8" stroke-width=".5"/>${(report.points||[]).map(p=>`<circle cx="${p.x}" cy="${b.height-p.y}" r=".7" fill="#4ade80"><title>${esc(p.ref)} (${p.x}, ${p.y}) ${p.rotation}°</title></circle>`).join('')}${project.marks.map((m,i)=>{const p=convert(m);return m.shape==='circle'?`<circle cx="${p.x}" cy="${p.y}" r="${m.width/2}" fill="none" stroke="#fbbf24" stroke-width=".5"><title>MARK ${i+1}</title></circle>`:`<rect x="${p.x-m.width/2}" y="${p.y-m.height/2}" width="${m.width}" height="${m.height}" fill="none" stroke="#fbbf24" stroke-width=".5"><title>MARK ${i+1}</title></rect>`;}).join('')}`;$('summary').textContent=`${b.width} × ${b.height} mm · ${report.summary.mounts} 点 · 库匹配 ${report.summary.matched}/${report.summary.groups}`;$('issues').innerHTML=report.errors.map(e=>`<div class="notice error">${esc(e.message)}${e.row!==undefined?` · 原行 ${e.row+1}`:''}</div>`).join('')+report.warnings.map(e=>`<div class="notice">${esc(e.message)}</div>`).join('');}
run(async()=>{markDefaults=await api('/mark-defaults');await listProjects();const id=new URLSearchParams(location.search).get('project');if(id)await openProject(id);})();
